Django/django_users/learning_users/basic_app/urls.py
from django .conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$',views.register,name="register"),
    url(r'^user_login/$',views.user_login,name="user_login"),
    url(r'logout/',views.user_logout,name="logout"),
    url(r'special/',views.special,name="special"),


]

Django/django_users/learning_users/learning_users/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [

    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django/django_users/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User)


    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to = 'profile_pics',blank = True)

    def __str__(self) :
        return self.user.username

Django/django_users/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Django/django_users/learning_users/basic_app/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse

from basic_app.forms import UserForm,UserProfileInfoForm

# Create your views here.


def index(request):
    return render(request,'basic_app/index.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
    
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

                profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    

    return render(request,'basic_app/registration.html',
                {'user_form':user_form,
                 'profile_form':profile_form,
                 'registered':registered
                 })

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user :
            if user.is_active:
                login(request,user) 
                return HttpResponseRedirect(reverse('index'))
            else:
              return HttpResponse("ACCOUNT NOT ACTIVE")

    
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}" .format(username,password))
            return HttpResponse("Invalid login details!")

    else:
        return render (request,'basic_app/login.html',)       




@login_required
def special(request):
        return render (request,'basic_app/special.html',)       



@login_required

def user_logout(request):

    logout(request)

    return HttpResponseRedirect(reverse('index'))

Django/django_users/learning_users/templates/basic_app/base.html
<html>
    <head>
        <title></title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    </head>

    <body>
        <nav class = "navbar navbar-default navbar-static-top">
            <div class = "container">
                <ul class = "nav navbar-nav">
                    <li> <a class ="navbar-brand" href = "{% url 'index' %}">DJANGo</a></li>
                    <li> <a class ="navbar-link" href = "{% url 'admin:index' %}">ADMIN</a></li>

                    <li> <a class ="navbar-link" href = "{% url 'basic_app:register' %}">REGISTER</a></li>
                    {% if user.is_authenticated %}
                    <li> <a class ="navbar-link" href = "{% url 'basic_app:logout' %}">LOGOUT</a></li>
                    <li> <a class ="navbar-link" href = "{% url 'basic_app:special' %}">SPECIAL</a></li>

                    {% else %}
                    <li> <a class ="navbar-link" href = "{% url 'basic_app:user_login' %}">LOGIN</a></li>
                    {% endif %}


                </ul>
            </div>
        </nav>

        <div class = "container">

            {% block body_block %}

       
        </div>

        {% endblock %}
    </body>
</html>

Django/django_users/learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class = "container">
    <h1>welcome to index!</h1>
    <img src="media/profile_pics/rabbit.jpg" alt="">

</div>

{% endblock %}

Django/django_users/learning_users/templates/basic_app/login.html
 {% extends "basic_app/base.html"%}


{% load staticfiles %}

{% block body_block %}

<div class = "jumbotron">
    <h1> Login  here</h1>

    <form action="{% url 'basic_app:user_login'%}" method = "POST">
        {% csrf_token %}

<label for="username">Username:</label>
<input type="text" name = "username" placeholder ="Enter Username"><br>

<label for="password">Password:</label>
<input type="password" name = "password"   placeholder="Enter Password"><br>

<button type = "submit" class ="btn btn-info">Login</button>
    </form>


   
</div>




{% endblock%} 

Django/django_users/learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html"%}


{% load staticfiles %}

{% block body_block %}

<div class = "jumbotron">


    {% if registered %}


    <h1> Thank you for registering</h1>

  

    {% else %}
    <h1> register  here</h1>

    <form enctype="multipart/form-data" method = "POST">

        {% csrf_token %}
        {{ user_form.as_p }}

        {{ profile_form.as_p }}

        <button type = "submit" class ="btn btn-info">Register</button>

    </form>

    {% endif %}
</div>




{% endblock%}

Django/django_users/learning_users/templates/basic_app/special.html
{% extends "basic_app/base.html"%}


{% load staticfiles %}

{% block body_block %}

<div class = "jumbotron">
    <h1> Hello and Welcome to special page</h1>
</div>




{% endblock%} 